name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: Log in to container registry
      uses: docker/login-action@v2
      with:
        registry: registry.hub.docker.com
        username: ${{ secrets.DH_USER }}
        password: ${{ secrets.DH_PASS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          hack3rru/demo-tms:github
